---
- name: Download configs to project dir
  fetch:
    src: "/var/www/staging/www/app/etc/{{ item }}"
    dest: "/var/www/{{ project }}/app/etc/"
    flat: yes
  with_items:
    - config.php
    - env.php

- name: Replace MySQL host value
  local_action:
    module: lineinfile
    path: "/var/www/{{ project }}/app/etc/env.php"
    regexp: "'host' => '"
    line: "                'host' => 'localhost:3306',"
  
- name: Replace DB name
  local_action:
    module: replace
    path: "/var/www/{{ project }}/app/etc/env.php"
    regexp: 'staging'
    replace: "{{ project | replace('-','_') }}"
