---
- name: Archive m1 project
  archive:
    path: /var/www/staging/www/
    dest: /tmp/project.tgz
    exclude_path:
    - /var/www/staging/www/var
    - /var/www/staging/www/includes/src
  when: project_type == 'm1'

- name: Archive m2 project
  archive:
    path: /var/www/staging/www/
    dest: /tmp/project.tgz
    exclude_path:
    - /var/www/staging/www/var
    - /var/www/staging/www/vendor
  when: project_type == 'm2'
