---
- name: Execute git gc
  shell: git gc
  args:
    chdir: "{{ project_root }}/"
  ignore_errors: true

- name: Archive m1 project without media
  shell: "tar --exclude=./var --exclude=./includes/src --exclude=./pub/static --exclude=./media -zcvf /envcopy/project_{{ project }}.tgz ."
  args:
    chdir: "{{ project_root }}"
  when: project_type == 'm1' and media_dump == 'false'

- name: Archive m2 project without media
  shell: "tar --exclude=./var --exclude=./vendor --exclude=./generated --exclude=./pub/static --exclude=./pub/media -zcvf /envcopy/project_{{ project }}.tgz ."
  args:
    chdir: "{{ project_root }}"
  when: project_type == 'm2' and media_dump == 'false'

- name: Archive m1 project
  shell: "tar --exclude=./var --exclude=./includes/src --exclude=./pub/static -zcvf /envcopy/project_{{ project }}.tgz ."
  args:
    chdir: "{{ project_root }}"
  when: project_type == 'm1' and media_dump == 'true'

- name: Archive m2 project
  shell: "tar --exclude=./var --exclude=./vendor --exclude=./generated --exclude=./pub/static -zcvf /envcopy/project_{{ project }}.tgz ."
  args:
    chdir: "{{ project_root }}"
  when: project_type == 'm2' and media_dump == 'true'

- name: Include vue tasks
  include_tasks: vue.yml
  when: vue_project is defined
