---
- name: Archive m1 project without media
  archive:
    path: "{{ project_root }}/."
    dest: "/envcopy/project_{{ project }}.tgz"
    exclude_path:
    - "{{ project_root }}/var"
    - "{{ project_root }}/includes/src"
    - "{{ project_root }}/media"
  when: project_type == 'm1' and media_dump == 'false'

- name: Archive m2 project without media
  archive:
    path: "{{ project_root }}/."
    dest: "/envcopy/project_{{ project }}.tgz"
    exclude_path:
    - "{{ project_root }}/var"
    - "{{ project_root }}/vendor"
    - "{{ project_root }}/pub/media"
  when: project_type == 'm2' and media_dump == 'false'

- name: Archive m1 project
  archive:
    path: "{{ project_root }}/."
    dest: "/envcopy/project_{{ project }}.tgz"
    exclude_path:
    - "{{ project_root }}/var"
    - "{{ project_root }}/includes/src"
  when: project_type == 'm1' and media_dump == 'true'

- name: Archive m2 project
  archive:
    path: "{{ project_root }}/."
    dest: "/envcopy/project_{{ project }}.tgz"
    exclude_path:
    - "{{ project_root }}/var"
    - "{{ project_root }}/vendor"
  when: project_type == 'm2' and media_dump == 'true'
