---
- name: Create mysql database
  command: "mysql -P {{ mysql_port }} --protocol=tcp -h127.0.0.1 -u{{ mysql_user_local }} -p{{ mysql_pass_local }} -e 'CREATE DATABASE IF NOT EXISTS {{ project | replace('-','_') }};'"
