---
- name: Download project
  shell: "rsync -r -v --progress  -e 'ssh -i {{ aws_private_key_path }}' {{ aws_username }}@{{ project }}.stgin.com:/tmp/project.tgz ./ > /dev/tty"
  args:
    chdir: "/var/www/{{ project }}/public/"
  become: true
