---
- name: Download vue project
  shell: "rsync -r -v --progress  -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i {{ aws_private_key_path }}' {{ aws_username }}@{{ project }}.stgin.com:/envcopy/project_{{ project }}_vue.tgz ./ > /dev/tty"
  args:
    chdir: "/var/www/{{ project }}/vue/"
  become: true

- name: Download vue-api project
  shell: "rsync -r -v --progress  -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i {{ aws_private_key_path }}' {{ aws_username }}@{{ project }}.stgin.com:/envcopy/project_{{ project }}_vue-api.tgz ./ > /dev/tty"
  args:
    chdir: "/var/www/{{ project }}/vue-api/"
  become: true
