---
- name: Unarchive project.tgz
  shell: tar xzvf project.tgz
  args: 
    chdir: "/var/www/{{ project }}/public/"
  become: true

- name: Delete project dump
  file:
    path: "/var/www/{{ project }}/public/project.tgz"
    state: absent
