---
php7_3_packages:
  - php7.3-common
  - php7.3-cli
  - php7.3-dev
  - php7.3-fpm
  - libpcre3-dev
  - php7.3-gd
  - php7.3-curl
  - php7.3-imap
  - php7.3-json
  - php7.3-opcache
  - php7.3-xml
  - php7.3-mbstring
  - php-imagick
  - php-apcu
  - php7.3-bcmath
  - php7.3-intl
  - php7.3-soap
  - php7.3-zip
  - php7.3-mysql

php7_4_packages:
  - php7.4-common
  - php7.4-cli
  - php7.4-dev
  - php7.4-fpm
  - libpcre3-dev
  - php7.4-gd
  - php7.4-curl
  - php7.4-imap
  - php7.4-json
  - php7.4-opcache
  - php7.4-xml
  - php7.4-mbstring
  - php-imagick
  - php-apcu
  - php7.4-bcmath
  - php7.4-intl
  - php7.4-soap
  - php7.4-zip
  - php7.4-mysql

php8_0_packages:
  - php8.0-common
  - php8.0-cli
  - php8.0-dev
  - php8.0-fpm
  - libpcre3-dev
  - php8.0-gd
  - php8.0-curl
  - php8.0-imap
  - php-json
  - php8.0-opcache
  - php8.0-xml
  - php8.0-mbstring
  - php-imagick
  - php-apcu
  - php8.0-bcmath
  - php8.0-intl
  - php8.0-soap
  - php8.0-zip
  - php8.0-mysql
