---
php5_6_packages:
  - php5.6-common
  - php5.6-cli
  - php5.6-dev
  - php5.6-fpm
  - libpcre3-dev
  - php5.6-gd
  - php5.6-curl
  - php5.6-imap
  - php5.6-json
  - php5.6-opcache
  - php5.6-xml
  - php5.6-mbstring
  - php-imagick
  - php-apcu
  - php5.6-bcmath
  - php5.6-intl
  - php5.6-soap
  - php5.6-mcrypt
  - php5.6-zip
  - php5.6-mysql

php7_0_packages:
  - php7.0-common
  - php7.0-cli
  - php7.0-dev
  - php7.0-fpm
  - libpcre3-dev
  - php7.0-gd
  - php7.0-curl
  - php7.0-imap
  - php7.0-json
  - php7.0-opcache
  - php7.0-xml
  - php7.0-mbstring
  - php-imagick
  - php-apcu
  - php7.0-bcmath
  - php7.0-intl
  - php7.0-soap
  - php7.0-mcrypt
  - php7.0-zip
  - php7.0-mysql

php7_1_packages:
  - php7.1-common
  - php7.1-cli
  - php7.1-dev
  - php7.1-fpm
  - libpcre3-dev
  - php7.1-gd
  - php7.1-curl
  - php7.1-imap
  - php7.1-json
  - php7.1-opcache
  - php7.1-xml
  - php7.1-mbstring
  - php-imagick
  - php-apcu
  - php7.1-bcmath
  - php7.1-intl
  - php7.1-soap
  - php7.1-mcrypt
  - php7.1-zip
  - php7.1-mysql
