---
# Variable setup.
- name: Add repository for PHP versions (Ubuntu).
  apt_repository: repo='ppa:ondrej/php'
  when: ansible_distribution == "Ubuntu"

- name: Add repository for PHP 5 compatibility packages (Ubuntu).
  apt_repository: repo='ppa:ondrej/php5-compat'
  when:
    - ansible_distribution == "Ubuntu" and ansible_distribution_version == '16.04'

- name: Add dependencies for PHP versions (Debian).
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - ca-certificates
  when: ansible_distribution == "Debian"

- name: Add Ondrej Sury's apt key (Debian).
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
  when: ansible_distribution == "Debian"

- name: Add Ondrej Sury's repo (Debian).
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present
  register: php_ondrej_debian_repo
  when: ansible_distribution == "Debian"

- name: Update apt caches after repo is added (Debian).
  apt: update_cache=yes
  when: php_ondrej_debian_repo.changed and (ansible_distribution == "Debian")

- name: Ensure PHP5.6 packages are installed.
  apt:
    name: "{{ php5_6_packages }}"
    state: "{{ php_packages_state }}"
    install_recommends: "{{ php_install_recommends }}"

- name: Ensure PHP7.0 packages are installed.
  apt:
    name: "{{ php7_0_packages }}"
    state: "{{ php_packages_state }}"
    install_recommends: "{{ php_install_recommends }}"
  register: php_package_install

- name: Ensure PHP7.1 packages are installed.
  apt:
    name: "{{ php7_1_packages }}"
    state: "{{ php_packages_state }}"
    install_recommends: "{{ php_install_recommends }}"
