---
vscode_extensions:
 - ue.alphabetical-sorter
 - formulahendry.auto-close-tag
 - RamiroBerrelleza.bitbucket-pull-requests
 - alefragnani.Bookmarks
 - CoenraadS.bracket-pair-colorizer
 - CoenraadS.bracket-pair-colorizer-2
 - msjsdiag.debugger-for-chrome
 - oouo-diogo-perdigao.docthis
 - mikestead.dotenv
 - psioniq.psi-header
 - EditorConfig.EditorConfig
 - mhutchie.git-graph
 - codezombiech.gitignore
 - eamodio.gitlens
 - nhoizey.gremlins
 - Zignd.html-css-class-completion
 - abusaidm.html-snippets
 - oderwat.indent-rainbow
 - christian-kohler.npm-intellisense
 - christian-kohler.path-intellisense
 - tomoki1207.pdf
 - kotfire.php-add-property
 - junstyle.php-cs-fixer
 - felixfbecker.php-debug
 - MehediDracula.php-namespace-resolver
 - xyz.plsql-language
 - esbenp.prettier-vscode
 - mohsen1.prettify-json
 - mtxr.sqltools
 - mtxr.sqltools-driver-mysql
 - mtxr.sqltools-driver-sqlite
 - TabNine.tabnine-vscode
 - octref.vetur
 - rvest.vs-code-prettier-eslint
 - ms-azuretools.vscode-docker
 - dbaeumer.vscode-eslint
 - GraphQL.vscode-graphql
 - bmewburn.vscode-intelephense-client
 - mrmlnc.vscode-scss
 - stylelint.vscode-stylelint
 - ms-vscode.vscode-typescript-tslint-plugin
 - redhat.vscode-yaml
 - gamunu.vscode-yarn
