- name: Download mysqldump to project dir
  shell: "rsync -r -v --progress -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i {{ aws_private_key_path }}' {{ aws_username }}@{{ project }}.stgin.com:/envcopy/web_{{ project }}.sql ./ > /dev/tty"
  args:
    chdir: "/var/www/{{ project }}/sql/"
