---
- name: Set project_type
  set_fact:
    project_type: "{{hostvars[item]['project_type']}}"
  with_items: "{{ project }}.stgin.com"

- name: Set mysql_db
  set_fact:
    mysql_db: "{{hostvars[item]['mysql_db']}}"
  with_items: "{{ project }}.stgin.com"

- name: Set table_prefix
  set_fact:
    table_prefix: "{{hostvars[item]['table_prefix']}}"
  with_items: "{{ project }}.stgin.com"

- name: Ensure nginx and mysql is running
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - nginx
    - mysql

- name: Get the username running the deploy
  local_action: command whoami
  register: username_on_the_host

- name: Print username
  debug: var=username_on_the_host.stdout

- name: Create project directories
  file:
    path: "{{ item }}"
    owner: "{{ username_on_the_host.stdout }}"
    group: www-data
    state: directory
  with_items:
    - /var/www
    - "/var/www/{{ project }}"
    - "/var/www/{{ project }}/public"
    - "/var/www/{{ project }}/logs"
    - "/var/www/{{ project }}/sql"
    - "/var/www/{{ project }}/public/app/etc"
  become: yes

- name: Create nginx vhost
  template:
    src: "{{ project_type }}.j2"
    dest: "/etc/nginx/sites-available/{{ project }}"
    mode: 0644
  become: yes

- name: Create link for status file
  file:
    src: "/etc/nginx/sites-available/{{ project }}"
    dest: "/etc/nginx/sites-enabled/{{ project }}"
    state: link
  notify:
    - restart nginx
  become: yes

- name: Update /etc/hosts file
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ project }} {{ project }}.local"
  become: yes
