---
- name: Create vue project directories
  file:
    path: "{{ item }}"
    owner: "{{ username_on_the_host.stdout }}"
    group: www-data
    state: directory
  with_items:
    - "/var/www/{{ project }}/vue"
    - "/var/www/{{ project }}/vue-api"
  become: yes

- name: Create Makefile
  template:
    src: 'Makefile'
    dest: "/var/www/{{ project }}/Makefile"
    mode: 0644
  become: yes
