---
- name: Create vue project directories
  file:
    path: "{{ item }}"
    owner: "{{ username_on_the_host.stdout }}"
    group: www-data
    state: directory
  with_items:
    - "/var/www/{{ project }}/vue"
    - "/var/www/{{ project }}/vue-api"
  become: yes

- name: Create vue nginx vhosts
  template:
    src: 'vue.j2'
    dest: "/etc/nginx/sites-available/{{ project }}-vue"
    mode: 0644
  become: yes

- name: Create link for vue project
  file:
    src: "/etc/nginx/sites-available/{{ project }}-vue"
    dest: "/etc/nginx/sites-enabled/{{ project }}-vue"
    state: link
  notify:
    - restart nginx
  become: yes

- name: Update /etc/hosts file for vue
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ project }}-vue {{ project }}-vue.local {{ project }}-vue-api {{ project }}-vue-api.local"
  become: yes
