---
- name: Get mysql size
  shell: du /var/lib/mysql | tail -n 1 | awk {'print $1 '}
  register: mysql_size

- name: Get project size
  shell: du /var/www | tail -n 1 | awk {'print $1 '}
  register: project_size

- name: Get free disk space
  shell: df / | tail -n 1 | awk {'print $4 '}
  register: available_disk_space

- name: Check disk space
  assert:
    that: "{{ mysql_size.stdout }} + {{ project_size.stdout }} < {{ available_disk_space.stdout }}"
    msg: Not enough disk space to copy project. Cleanup your project or resize disk.
  
