---
- name: Ensure nginx and mysql is running
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - nginx
    - mysql

- name: Get the username running the deploy
  local_action: command whoami
  register: username_on_the_host

- name: Print username
  debug: var=username_on_the_host.stdout

- name: Set local media path
  set_fact:
    media_path_local: "{% if project_type == 'm2' %}/var/www/{{ project }}/pub/media{% else %}/var/www/{{ project }}/media{% endif %}"

- name: Create project directories
  file:
    path: "{{ item }}"
    owner: "{{ username_on_the_host.stdout }}"
    group: www-data
    state: directory
  with_items:
    - /var/www
    - "/var/www/{{ project }}"
    - "/var/www/{{ project }}/public"
    - "/var/www/{{ project }}/logs"
    - "/var/www/{{ project }}/sql"
    - "/var/www/{{ project }}/app/etc"
    - "{{ media_path_local }}"
  become: yes

- name: Create nginx vhost
  template:
    src: "{{ project_type }}.j2"
    dest: "/etc/nginx/sites-available/{{ project }}"
    mode: 0644
  become: yes

- name: Create link for status file
  file:
    src: "/etc/nginx/sites-available/{{ project }}"
    dest: "/etc/nginx/sites-enabled/{{ project }}"
    state: link
  notify:
    - restart nginx
  become: yes

- name: Update /etc/hosts file
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ project }} {{ project }}.local"
  become: yes
