---
- name: check mount point /envcopy
  command: mountpoint /envcopy
  register: mount_stat
  failed_when: False
  changed_when: False

- name: umount NFS
  shell: umount /envcopy
  when: mount_stat.stdout != '/envcopy is not a mountpoint'
