---
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
     - register-ec2host

- hosts: ec2host
  remote_user: "{{ aws_username }}"
  become: true
  gather_facts: true
  roles:
     - nfs/umount
     - nfs/mount
     - magento/version

- hosts: localhost
  connection: local
  become: true
  gather_facts: false
  roles:
     - env/create

- hosts: ec2host
  remote_user: "{{ aws_username }}"
  become: true
  gather_facts: true
  roles:
     - mysql/dump
     - role: project/dump
       when: project_dump == 'true'
    
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
     - mysql/scp
     - mysql/restore
     - role: project/scp
       when: project_dump == 'true'
     - role: project/restore
       when: project_dump == 'true'
     - own

- hosts: ec2host
  remote_user: "{{ aws_username }}"
  become: true
  gather_facts: true
  roles:
     - configs
     - mysql/remove
     - role: project/remove
       when: project_dump == 'true'
     - nfs/umount

