# ../ansible-playbook -K -i localhost, playbooks/envcopy.yml -e project=biobag-ie -e project_type=m2 -e aws_username=vitalijs.volodenkovs
---
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
     - env
     - register-ec2host

- hosts: ec2host
  remote_user: "{{ aws_username }}"
  become: true
  gather_facts: true
  roles:
#     - mysql/dump
#     - media/dump
     - configs
    
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
#     - mysql/scp
     - mysql/restore
#     - media/scp
#     - media/restore

#- hosts: ec2host
#  remote_user: "{{ aws_username }}"
#  become: true
#  gather_facts: true
#  roles:
#     - mysql/remove
#     - media/remove
