---
- hosts: localhost
  connection: local
  gather_facts: true
  become: true
  roles:
     - pcsetup/screen/turnoff
     - pcsetup/nginx
     - pcsetup/php
     - pcsetup/percona-server
     - pcsetup/guake
     - pcsetup/slack
     - pcsetup/phpstorm
     - pcsetup/chrome
     - { role: pcsetup/screen/launcher, when: ansible_distribution == "Ubuntu" and ansible_distribution_version == '16.04' }
     - pcsetup/screen/turnon
