---
- hosts: localhost
  connection: local
  gather_facts: true
  become: true
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: no
    - name: name
      prompt: What is your Name?
      private: no
    - name: surname
      prompt: What is your Surname?
      private: no
  pre_tasks:
  - name: install libutempter0
    apt:
      name: libutempter0
      state: present
    when: ansible_distribution_release == 'bionic'
  roles:
     - pcsetup/screen/turnoff
     - pcsetup/docker
     - pcsetup/elasticsearch
     - pcsetup/nginx
     - pcsetup/php
     - pcsetup/composer
     - pcsetup/guake
     - pcsetup/slack
     - pcsetup/vscode
     - pcsetup/chrome
     - pcsetup/screen/launcher
     - pcsetup/l2tp
     - pcsetup/screen/turnon
  post_tasks:
  - name: Install mysql client
    apt:
      name: mysql-client
  - name: Create MySQL 8 container
    docker_container:
      name: mysql8
      state: started
      restart: yes
      restart_policy: always
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      ports:
      - "3307:3306"
      env:
        MYSQL_ROOT_HOST: "%"
        MYSQL_ROOT_PASSWORD: "option123"
      volumes:
      - "mysql8:/var/lib/mysql:rw"
  - name: Create MySQL 5.7 container
    docker_container:
      name: mysql57
      state: started
      restart: yes
      restart_policy: always
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      ports:
      - "3306:3306"
      env:
        MYSQL_ROOT_HOST: "%"
        MYSQL_ROOT_PASSWORD: "option123"
      volumes:
      - "mysql57:/var/lib/mysql:rw"
