---
- hosts: localhost
  connection: local
  gather_facts: true
  become: true
  pre_tasks:
  - name: install libutempter0
    apt:
      name: libutempter0
      state: present
    when: ansible_distribution_release == 'bionic'
  roles:
     - pcsetup/screen/turnoff
     - pcsetup/nginx
     - pcsetup/php
     - pcsetup/composer
     - pcsetup/percona-server
     - pcsetup/guake
     - pcsetup/slack
     - pcsetup/phpstorm
     - pcsetup/chrome
     - { role: pcsetup/screen/launcher, when: ansible_distribution == "Ubuntu" and ansible_distribution_version == '16.04' }
     - pcsetup/screen/turnon
