---
- hosts: localhost
  connection: local
  gather_facts: true
  become: true
  roles:
     - pcsetup/nginx
     - pcsetup/percona-server
     - pcsetup/guake
     - pcsetup/slack
     - pcsetup/phpstorm
     - pcsetup/chrome
